### PR TITLE
Add Remove function to LinkedList

### PR DESCRIPTION
**Pull request by greg80303**
This change adds support for the PARCList.Remove() function in PARCLinkedList.

As part of this change I consolidated the code that removes a node from the list into a single function - `_parkLinkedListNode_RemoveNoChecks`.  This function safely removes the node from any point in the list and conditionally releases the underlying object (`bool releaseObj` parameter).  The reason for the conditional release is that the addition of the `parcLinkedList_Remove` function introduces a case where we need to automatically release the object, whereas `parcLinkedList_RemoveFirst` and `parcLinkedList_RemoveLast` do not.

Also added 2 new unit tests for the Remove function

### CODE REVIEW

**Comment by GlennCScott** [comment]
Hi Greg,
  This is great, thank you.

  A comment I have is an function that takes a boolean to toggle it's behavior is really two functions crammed into one.   It's a small matter here, because the functions are static and not exposed to the primary API, but in the interest of setting a good example, let's split:

 `_parcLinkedListNode_Destroy(PARCLinkedList *, _PARCLinkedListNode **, bool) `

into two functions with their intent clear from their names.  Something like:

 `_parcLinkedListNode_DestroyAndRelease(PARCLinkedList *, _PARCLinkedListNode **) `

 `_parcLinkedListNode_DestroyAndNoRelease(PARCLinkedList *, _PARCLinkedListNode **) `

What do you think?

Glenn

**Comment by isolis** [comment]
I would favor using the bool toggle.  

Part of the issue here is that there is some logic needed about when to release and when not to release. This means that there is logic that is needed to determine this.  

Any caller function that only expects one behavior will be happy either way, using the bool or not. In one case, it will hard-code the function. In the other, it will hard code the parameter.  However, a function that can do both will have to add logic to determine which of the 2 functions to call if we split the function.

That same logic, we can do right at the end, when, once we find a pointer to an object, we need to decide whether to release or not.  

I favor putting that logic at the end.  It's highly likely that many of the functions that use it (and this function itself) has a lot of modularity, so splitting it into 2 functions will just create more code to maintain.

Now if anything changes we will have to change 2 functions.  I assume this will lead to the creation of some sub-functions with the shared functionality, which will eventually turn into a function that does the equivalent of a search_and_destroy function, followed by a potential release.  In this case, it's possible it works out, but in other cases, when the decision needs to be made in the middle (release before destroy) it creates more code.

So, I would rather keep the boolean flag.

Having said all that, if the functions are not exposed by the API now, it might not matter much, but I would still like to keep the function as one.

**Comment by greg80303** [comment]
Oops, well I pushed the split functions with e135181 before I saw Nacho's comments.  Please let me know if I should back that change out.

**Comment by isolis** [comment]
I won't object to the split functions, I was just stating my preference.

**Comment by GlennCScott** [comment]
Sorry, it’s a known anti-pattern.  “You’ve got one job.”  See, for example:

design - Is it wrong to use a boolean parameter to determine behavior? - Programmers Stack Exchange<https://programmers.stackexchange.com/questions/147977/is-it-wrong-to-use-a-boolean-parameter-to-determine-behavior>

Glenn



On Mar 2, 2016, at 10:54 AM, Ignacio Solis <notifications@github.com<mailto:notifications@github.com>> wrote:


I would favor using the bool toggle.

Part of the issue here is that there is some logic needed about when to release and when not to release. This means that there is logic that is needed to determine this.

Any caller function that only expects one behavior will be happy either way, using the bool or not. In one case, it will hard-code the function. In the other, it will hard code the parameter. However, a function that can do both will have to add logic to determine which of the 2 functions to call if we split the function.

That same logic, we can do right at the end, when, once we find a pointer to an object, we need to decide whether to release or not.

I favor putting that logic at the end. It's highly likely that many of the functions that use it (and this function itself) has a lot of modularity, so splitting it into 2 functions will just create more code to maintain.

Now if anything changes we will have to change 2 functions. I assume this will lead to the creation of some sub-functions with the shared functionality, which will eventually turn into a function that does the equivalent of a search_and_destroy function, followed by a potential release. In this case, it's possible it works out, but in other cases, when the decision needs to be made in the middle (release before destroy) it creates more code.

So, I would rather keep the boolean flag.

Having said all that, if the functions are not exposed by the API now, it might not matter much, but I would still like to keep the function as one.

**Comment by GlennCScott** [comment]
Greg would you mind if I pulled your changes into my internal Libparc to be pushed back out to github in a few days?

**Comment by isolis** [comment]
Yeah, I disagree with this argument (pun not intended).

I do agree that reading some code where the parameter is just an actual boolean is hard.  So I'm not in favor of just doing "True" or "False".  However, I don't think having a function that does 90% of the work, then destroys and another function that does the same 90% and not destroys is warranted.

I could argue that if I wanted to be clean the function wouldn't do any of these. It would just return something and the caller would the choose what to do. Single function.  Let the caller figure out if they want to.  The reason we end up with a function it's because it's a repeating pattern, no?

Having 2 functions for this means that if I have some structure above this, I will have to have 2 functions for that as well.  That means 2 more functions to maintain. And the same would be true above that, etc.

I'm not advocating that boolean parameter are right all the time, far from it. But there are situations when an argument with 2 values is reasonable behavior.

**Comment by greg80303** [comment]
@GlennCScott Of course.  I have my own branch to work off of.  And please let me know if there are other changes you'd like me to make.

**Comment by GlennCScott** [comment]
Granted, if you have two or more functions, each of which implement code that is, say, 90% the same… you have improperly factored your code.  Not that you’ve made a reasonable argument for implementing some kind of Pachinko machine function where the user has toggles they must set to improve their chance of success.

Glenn

**Comment by GlennCScott** [comment]
I'm going to pull this into my local repository as I also have changes to parc_LinkedList.  I will get your functionality in there.

**Comment by GlennCScott** [comment]
Greg,
  Could you take a look at what I implemented and see if that's what you want?  I had some other changes that went in as well.

**Comment by greg80303** [comment]
@GlennCScott Looks good.  Feel free to delete this PR.  Thanks!

**Comment by GlennCScott** [comment]
Thanks!

**Pull request closed without merging**
